using Server.Factions;
using Server.Mobiles;

using System;
using System.Collections.Generic;

namespace Server
{
	public partial class SpeedInfo
	{
		private static Dictionary<Type, SpeedInfo> m_Table;

		private static readonly SpeedInfo[] m_Speeds = new SpeedInfo[]
		{
            #region MOBILE MOVEMENT.....................................[ - SLOW - ]

            new SpeedInfo( 0.3, 0.6, new Type[]
				{
					typeof( AntLion ),
					typeof( Bogle ),
					typeof( Ettin ),
					typeof( GazerLarva ),
					typeof( HeadlessOne ),
					typeof( Ogre ),
					typeof( Quagmire ),
					typeof( Sewerrat ),
					typeof( Zombie ),
					typeof( CrystalElemental ),
					typeof( Juggernaut ),
					typeof( ArcticOgreLord ),
					typeof( BoneKnight ),
					typeof( FrostOoze ),
					typeof( Ghoul ),
					typeof( Jwilson ),
					typeof( OgreLord ),
					typeof( Rat ),
					typeof( Skeleton ),
					typeof( Walrus ),
					typeof( DarknightCreeper ),
					typeof( Yamandon ),
					typeof( BogThing ),
					typeof( EarthElemental ),
					typeof( FrostTroll ),
					typeof( Golem ),
					typeof( Mummy ),
					typeof( PlagueBeast ),
					typeof( RottingCorpse ),
					typeof( Slime ),
					typeof( RestlessSoul ),
					typeof( MoundOfMaggots ),
					typeof( Serado )
				} ),

            #endregion

            #region MOBILE MOVEMENT...................................[ - MEDIUM - ]

            new SpeedInfo( 0.25, 0.5, new Type[]
				{
					typeof( AcidElemental ),
					typeof( AncientLich ),
					typeof( BlackBear ),
					typeof( BlackSolenQueen ),
					typeof( BloodElemental ),
					typeof( BoneMagi ),
					typeof( BrownBear ),
					typeof( Cat ),
					typeof( Chicken ),
					typeof( CopperElemental ),
					typeof( Cyclops ),
					typeof( DesertOstard ),
					typeof( Dolphin ),
					typeof( DullCopperElemental ),
					typeof( EvilMage ),
					typeof( Savage ),
					typeof( FireSteed ),
					typeof( FrostSpider ),
					typeof( IceSerpent ),
					typeof( GiantSpider ),
					typeof( GoldenElemental ),
					typeof( GreyWolf ),
					typeof( Harpy ),
					typeof( Hind ),
					typeof( Horse ),
					typeof( IceSnake ),
					typeof( Kirin ),
					typeof( LavaLizard ),
					typeof( Lizardman ),
					typeof( StrongMongbat ),
					typeof( OrcBomber ),
					typeof( OrcishLord ),
					typeof( PackLlama ),
					typeof( PlagueSpawn ),
					typeof( Ratman ),
					typeof( RedSolenInfiltratorQueen ),
					typeof( RedSolenWarrior ),
					typeof( Ridgeback ),
					typeof( SerpentineDragon ),
					typeof( ShadowWisp ),
					typeof( SilverSteed ),
					typeof( SkeletalMount ),
					typeof( SnowLeopard ),
					typeof( StoneGargoyle ),
					typeof( ScaledSwampDragon ),
					typeof( TerathanDrone ),
					typeof( TimberWolf ),
					typeof( Unicorn ),
					typeof( CoMWarHorse ),
					typeof( TBWarHorse ),
					typeof( WhiteWolf ),
					typeof( KhaldunZealot ),
					typeof( LichLord ),
					typeof( SummonedEarthElemental ),
					typeof( MeerWarrior ),
					typeof( MeerCaptain ),
					typeof( JukaWarrior ),
					typeof( Devourer ),
					typeof( GoreFiend ),
					typeof( Ravager ),
					typeof( Treefellow ),
					typeof( WandererOfTheVoid ),
					typeof( SpectralArmour ),
					typeof( Doppleganger ),
					typeof( ExodusOverseer ),
					typeof( Moloch ),
					typeof( Kappa ),
					typeof( TsukiWolf ),
					typeof( YomotsuWarrior ),
					typeof( Gaman ),
					typeof( AgapiteElemental ),
					typeof( Betrayer ),
					typeof( BlackSolenInfiltratorQueen ),
					typeof( BlackSolenWarrior ),
					typeof( Boar ),
					typeof( Brigand ),
					typeof( Bull ),
					typeof( Centaur ),
					typeof( GolemController ),
					typeof( Cougar ),
					typeof( Daemon ),
					typeof( DireWolf ),
					typeof( Dragon ),
					typeof( Eagle ),
					typeof( EvilMageLord ),
					typeof( FireElemental ),
					typeof( ForestOstard ),
					typeof( Gargoyle ),
					typeof( GiantRat ),
					typeof( GiantToad ),
					typeof( Gorilla ),
					typeof( GrizzlyBear ),
					typeof( Harrower ),
					typeof( HordeMinion ),
					typeof( IceElemental ),
					typeof( Imp ),
					typeof( Kraken ),
					typeof( LavaSerpent ),
					typeof( Llama ),
					typeof( MountainGoat ),
					typeof( OrcBrute ),
					typeof( OrcishMage ),
					typeof( Panther ),
					typeof( PolarBear ),
					typeof( RatmanArcher ),
					typeof( RedSolenInfiltratorWarrior ),
					typeof( RedSolenWorker ),
					typeof( Scorpion ),
					typeof( Shade ),
					typeof( ShadowWyrm ),
					typeof( SkeletalDragon ),
					typeof( HellCat ),
					typeof( SpectralArmour ),
					typeof( StoneHarpy ),
					typeof( SwampTentacle ),
					typeof( TerathanMatriarch ),
					typeof( Titan ),
					typeof( ValoriteElemental ),
					typeof( MinaxWarHorse ),
					typeof( WaterElemental ),
					typeof( Wraith ),
					typeof( KhaldunSummoner ),
					typeof( SkeletalKnight ),
					typeof( SummonedWaterElemental ),
					typeof( MeerEternal ),
					typeof( JukaLord ),
					typeof( AbysmalHorror ),
					typeof( FleshGolem ),
					typeof( Impaler ),
					typeof( ShadowKnight ),
					typeof( VampireBat ),
					typeof( Cursed ),
					typeof( EnslavedGargoyle ),
					typeof( GargoyleDestroyer ),
					typeof( BakeKitsune ),
					typeof( KazeKemono ),
					typeof( YomotsuElder ),
					typeof( RevenantLion ),
					typeof( Crane ),
					typeof( Alligator ),
					typeof( Bird ),
					typeof( BlackSolenInfiltratorWarrior ),
					typeof( BlackSolenWorker ),
					typeof( Bogling ),
					typeof( BronzeElemental ),
					typeof( BullFrog ),
					typeof( ChaosDaemon ),
					typeof( CopperElemental ),
					typeof( Cow ),
					typeof( DeepSeaSerpent ),
					typeof( Dog ),
					typeof( Drake ),
					typeof( ElderGazer ),
					typeof( Executioner ),
					typeof( FireGargoyle ),
					typeof( FrenziedOstard ),
					typeof( Gazer ),
					typeof( GiantSerpent ),
					typeof( Goat ),
					typeof( GreatHart ),
					typeof( Guardian ),
					typeof( HellHound ),
					typeof( Horse ),
					typeof( IceFiend ),
					typeof( JackRabbit ),
					typeof( PredatorHellCat ),
					typeof( LavaSnake ),
					typeof( Mongbat ),
					typeof( Orc ),
					typeof( OrcCaptain ),
					typeof( PackHorse ),
					typeof( Pig ),
					typeof( Rabbit ),
					typeof( RatmanMage ),
					typeof( RedSolenQueen ),
					typeof( RidableLlama ),
					typeof( SeaSerpent ),
					typeof( ShadowIronElemental ),
					typeof( Sheep ),
					typeof( SkeletalMage ),
					typeof( Snake ),
					typeof( Spectre ),
					typeof( SwampDragon ),
					typeof( TerathanAvenger ),
					typeof( TerathanWarrior ),
					typeof( Troll ),
					typeof( VeriteElemental ),
					typeof( SLWarHorse ),
					typeof( WhippingVine ),
					typeof( Wyvern ),
					typeof( SavageRidgeback ),
					typeof( SummonedDaemon ),
					typeof( SummonedFireElemental ),
					typeof( MeerMage ),
					typeof( JukaMage ),
					typeof( BoneDemon ),
					typeof( Gibberling ),
					typeof( PatchworkSkeleton ),
					typeof( SkitteringHopper ),
					typeof( WailingBanshee ),
					typeof( ShadowFiend ),
					typeof( ArcaneDaemon ),
					typeof( ExodusMinion ),
					typeof( GargoyleEnforcer ),
					typeof( DeathwatchBeetleHatchling ),
					typeof( DeathwatchBeetle ),
					typeof( YomotsuPriest ),
					typeof( Oni ),
					typeof( Beetle )
				} ),

            #endregion

            #region MOBILE MOVEMENT.....................................[ - FAST - ]

            new SpeedInfo( 0.2, 0.4, new Type[]
				{
					typeof( LordOaks ),
					typeof( AncientWyrm ),
					typeof( DreadSpider ),
					typeof( Lich ),
					typeof( OphidianMage ),
					typeof( OphidianKnight ),
					typeof( SandVortex ),
					typeof( SnowElemental ),
					typeof( DemonKnight ),
					typeof( LesserHiryu ),
					typeof( RaiJu ),
					typeof( Changeling ),
					typeof( LadyJennifyr ),
					typeof( MasterMikael ),
					typeof( SirPatrick ),
					typeof( Grobu ),
					typeof( Irk ),
					typeof( LadySabrix ),
					typeof( Virulent ),
					typeof( Silvani ),
					typeof( Balron ),
					typeof( Efreet ),
					typeof( Nightmare ),
					typeof( OphidianWarrior ),
					typeof( PoisonElemental ),
					typeof( SavageRider ),
					typeof( WhiteWyrm ),
					typeof( GiantBlackWidow ),
					typeof( Hiryu ),
					typeof( Ronin ),
					typeof( LadyMarai ),
					typeof( Miasma ),
					typeof( Gnaw ),
					typeof( Spite ),
					typeof( Malefic ),
					typeof( AirElemental ),
					typeof( BladeSpirits ),
					typeof( EtherealWarrior ),
					typeof( OphidianArchmage ),
					typeof( OphidianMatriarch ),
					typeof( Revenant ),
					typeof( SavageShaman ),
					typeof( Wisp ),
					typeof( SummonedAirElemental ),
					typeof( LadyOfTheSnow ),
					typeof( RuneBeetle ),
					typeof( MasterJonath ),
					typeof( RedDeath ),
					typeof( Rend ),
					typeof( Guile ),
					typeof( LadyLissith ),
					typeof( Silk )
				} ),

            #endregion

            #region MOBILE MOVEMENT................................[ - VERY FAST - ]

            new SpeedInfo( 0.175, 0.350, new Type[]
				{
					typeof( Barracoon ),
					typeof( Rikktor ),
					typeof( EliteNinja ),
					typeof( VorpalBunny ),
					typeof( FactionDragoon ),
					typeof( FactionHenchman ),
					typeof( FactionSorceress ),
					typeof( FactionPaladin ),
					typeof( FanDancer ),
					typeof( Mephitis ),
					typeof( Semidar ),
					typeof( Pixie ),
					typeof( FleshRenderer ),
					typeof( FactionKnight ),
					typeof( FactionMercenary ),
					typeof( FactionWizard ),
					typeof( Leviathan ),
					typeof( FactionDeathKnight ),
					typeof( Neira ),
					typeof( EnergyVortex ),
					typeof( SilverSerpent ),
					typeof( FactionPaladin ),
					typeof( FactionNecromancer ),
					typeof( FactionBerserker ),
					typeof( FireBeetle )
				} )

            #endregion
        };
	}
}